language: node_js

node_js:
  - "lts/*"
  - "node"

os:
  - windows

# safelist
branches:
  only:
  - master
  - develop
  - hotfix
  - /^greenkeeper/.*$/

script: echo "Running tests against $(node -v)..."

# jobs:
#   include:
#     - stage: Produce Coverage
#       node_js: node
#       script: npm run jest